"""empty message

Revision ID: 411e8aecde94
Revises: fcd9cdfec5ef
Create Date: 2026-08-03 23:50:22.510375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411e8aecde94'
down_revision: Union[str, Sequence[str], None] = 'fcd9cdfec5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck_tasks', sa.Column('attempt_count', sa.INTEGER(), nullable=False))
    op.add_column('deck_tasks', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck_tasks', 'next_retry_at')
    op.drop_column('deck_tasks', 'attempt_count')
    # ### end Alembic commands ###
