"""empty message

Revision ID: 414cee3c802e
Revises: ce25e0af5250
Create Date: 2026-02-02 16:30:58.833349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414cee3c802e'
down_revision: Union[str, Sequence[str], None] = 'ce25e0af5250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deck_items', 'normalized_word',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('deck_items', 'sentence',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('deck_items', 'translation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('deck_items', 'error',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deck_items', 'error',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('deck_items', 'translation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('deck_items', 'sentence',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('deck_items', 'normalized_word',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
