"""empty message

Revision ID: 9e361e915255
Revises: bfdb85b00503
Create Date: 2026-01-17 01:00:55.096981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e361e915255'
down_revision: Union[str, Sequence[str], None] = 'bfdb85b00503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('current_stage', sa.TEXT(), nullable=False),
    sa.Column('total_items', sa.INTEGER(), nullable=False),
    sa.Column('completed_items', sa.INTEGER(), nullable=False),
    sa.Column('failed_items', sa.INTEGER(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('raw_word', sa.TEXT(), nullable=False),
    sa.Column('normalized_word', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('stage', sa.TEXT(), nullable=False),
    sa.Column('sentence', sa.TEXT(), nullable=False),
    sa.Column('translation', sa.TEXT(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['deck_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_items')
    op.drop_table('deck_tasks')
    # ### end Alembic commands ###
