"""empty message

Revision ID: ce25e0af5250
Revises: 37bd194768f6
Create Date: 2026-02-02 00:38:12.314943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce25e0af5250'
down_revision: Union[str, Sequence[str], None] = '37bd194768f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deck_tasks', 'error',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deck_tasks', 'error',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
